### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by cheeem** [cheeem/Dynamic-Metronome#1]
- [x] Make addBeat into its own component, included in Bar
- [x] Pass just beat obj as prop for beat.js
- [x] Add in traversing notes with metronome
- [x] Add sounds
- [x] Add option to change tempo
- [x] Add option to delete notes
- [x] Add option to change note sounds
- [x] Add option to change beat type
- [ ] Make a modules file for functions like useInterval
- [ ] Simplify App.js return with more components
- [x] Make functions to turn an array of values and text into option tags in each select
- [x] Create menu layout
- [x] Change menu to select specific notes, not beats (identified with object with beatCount and noteCount)
- [x] Have menu reset dropdowns based on the selected beat
- [x] Change function toggleMenu to displayMenu
- [x] Fix various deleting bugs
- [x] Replace beatCount with index/index+1
- [ ] Add option for users to input their own sound (create state for dropdown options)
- [x] Pass down selected sound to the specific note
- [ ] Include styles as a part of noteList array
- [x] Change noteList to notes
- [x] Change html icon
- [x] Move sound imports to App.css
- [x] Add state for adjusting volume
- [x] Make it so a note only plays once so rerenders do not impact note sounds
- [ ] Add the option for users to layer multiple or no sounds (checkbox?)
- [x] Make min/calc values for everything to prevent items from getting too small on smaller viewports
- [x] Add more sounds
- [x] Add hover animations for delete
- [x] Add hover animations for add beat
- [x] Add hover animations for buttons
- [x] Add hover animations for each note
- [ ] Add select animations for each note
- [ ] Add instruction labels (ex. Click a note to modify it, Set a tempo)
- [ ] Add an indication of how many notes are in each beat type in the dropdown
- [ ] Come up with different names for the sounds (emojis??)
- [x] Find a different font
- [x] Change the font weight of the menu labels
- [x] Create option for no sound
- [ ] Make no sound beats turn grey
- [x] Fix bug that stops the metronome when the user deletes a beat on a sub-note
- [ ] Css animations on load and while playing?
- [ ] Fade out deleted beats with [react CSSTransitions](https://www.youtube.com/watch?v=dwIyD0xaN_0) 
- [ ] Reposition menu when the note type changes (get the x/y position within the div of the note and note the page??)
- [ ] Add transitions to hover animations
- [x] Toggle metronome -> Start/Stop Metronome
- [ ] Create a more visual/easy to use way to change and delete notes/beats
- [ ] Fix bug that passes on sounds from delete beats
- [ ] Add better functionality (event listeners) for mobile devices
- [ ] Color themes
- [ ] Include emojis on each note to represent their sound
- [ ] Change tempo input to placeholder text after clicking change tempo [example](https://emojidb.org/kick-drum-emojis?user_typed_query=1&utm_source=user_search)
- [ ] Add the ability to select and update multiple notes
- [ ] Clean up your code 
- [ ] Create custom embed card
